/**
 * DRAFT, pending human review.
 * Protector content, Spanish. Source: the school's handout (master for the
 * 12 original typologies). DISS and IMPL translated from the English draft.
 * `wound` in tentative voice; `sourceWound` keeps the handout wording.
 */
import type { ProtectorKey } from "@/lib/scoring/types";
import type { Typology } from "./typologies.en";

export const MICRO_QUESTION_ES = "¿De qué me estás protegiendo, qué me evitas sentir o recordar cuando haces esto?";

export const TYPOLOGIES_ES: Record<ProtectorKey, Typology> = {
  PERF: {
    key: "PERF", name: "Perfeccionista / Exigente", role: "Manager (Gestor)", proposed: false,
    triggers: "Evaluación, error, comparación, tareas con estándar alto, exposición pública.",
    visibleBehaviour: "Corrige, revisa, no entrega, se sobreexige, busca \"lo perfecto\".",
    strategy: "\"Si lo hago perfecto, estoy a salvo\".",
    wound: "Partes como esta suelen proteger una vergüenza ligada al error, una sensación de no ser suficiente y un miedo a la humillación o al rechazo.",
    sourceWound: "Vergüenza por error; \"no soy suficiente\"; miedo a humillación o rechazo.",
    cost: "Ansiedad, rigidez, procrastinación, poco disfrute, desgaste relacional.",
    protectiveNeed: "Seguridad y aceptación a través del rendimiento.",
  },
  CRIT: {
    key: "CRIT", name: "Crítico / Juez", role: "Manager (Gestor)", proposed: false,
    triggers: "Vulnerabilidad, feedback, dudas internas, \"fallos\" propios o ajenos.",
    visibleBehaviour: "Descalifica, moraliza, endurece el tono interno o externo, señala defectos.",
    strategy: "Atacar antes de ser atacado; \"si te critico yo primero, afuera no te dañan\".",
    wound: "Partes como esta suelen proteger una historia de crítica o humillación, y a una parte más joven que carga vergüenza y miedo.",
    sourceWound: "Historia de crítica o humillación; exiliado con vergüenza y miedo.",
    cost: "Autocastigo, culpa, congelamiento, hostilidad, distancia afectiva.",
    protectiveNeed: "Evitar la exposición y mantener el control.",
  },
  PLEA: {
    key: "PLEA", name: "Complaciente", role: "Manager (Gestor)", proposed: false,
    triggers: "Conflicto, desaprobación, figuras de autoridad, poner límites.",
    visibleBehaviour: "Dice que sí, se adapta, evita contradecir, se sobrerresponsabiliza.",
    strategy: "Mantener la armonía para asegurar el vínculo.",
    wound: "Partes como esta suelen proteger un miedo al abandono o al rechazo, y una necesidad temprana de agradar para sentirse a salvo.",
    sourceWound: "Miedo a abandono o rechazo; necesidad temprana de agradar para estar seguro/a.",
    cost: "Resentimiento, agotamiento, identidad difusa, límites débiles.",
    protectiveNeed: "Pertenencia y seguridad relacional.",
  },
  CTRL: {
    key: "CTRL", name: "Controlador / Planificador", role: "Manager (Gestor)", proposed: false,
    triggers: "Incertidumbre, cambios, ambigüedad, depender de otra persona.",
    visibleBehaviour: "Agenda rígida, reglas, supervisa, corrige, anticipa escenarios.",
    strategy: "Predecir y controlar para estar a salvo.",
    wound: "Partes como esta suelen proteger a una parte más joven que conoció la imprevisibilidad o el caos, y que carga miedo e indefensión.",
    sourceWound: "Imprevisibilidad/caos temprano; exiliado con miedo e indefensión.",
    cost: "Tensión crónica, irritabilidad, rigidez, dificultad para delegar.",
    protectiveNeed: "Estabilidad y prevención del daño.",
  },
  INTL: {
    key: "INTL", name: "Intelectualizador / Racionalizador", role: "Manager (Gestor)", proposed: false,
    triggers: "Emoción intensa, intimidad, dolor, culpa, ambivalencia, conversación afectiva.",
    visibleBehaviour: "Analiza, teoriza, debate, explica; se desconecta del cuerpo.",
    strategy: "Convertir la emoción en pensamiento para regular la intensidad.",
    wound: "Partes como esta suelen proteger un dolor o una vergüenza que un día fueron \"demasiado\", y un miedo a desbordarse.",
    sourceWound: "Dolor/vergüenza \"demasiado\"; miedo a desbordarse.",
    cost: "Desconexión emocional, poca intimidad, vacío, dificultad para pedir apoyo.",
    protectiveNeed: "Evitar la vulnerabilidad y el desborde; mantener claridad y certeza.",
  },
  AVOI: {
    key: "AVOI", name: "Evitador / Procrastinador", role: "Manager (Gestor)", proposed: false,
    triggers: "Tareas con riesgo de fallo, evaluación, decisiones, objetivos importantes.",
    visibleBehaviour: "Pospone, se distrae, evita empezar, busca alivio inmediato.",
    strategy: "Evitar la activación ansiosa y la exposición a la evaluación.",
    wound: "Partes como esta suelen proteger una vergüenza anticipada, un miedo a fracasar y una sensación de impotencia.",
    sourceWound: "Vergüenza anticipada; miedo a fracasar; impotencia.",
    cost: "Culpa, oportunidades perdidas, presión acumulada, autoconcepto dañado.",
    protectiveNeed: "Reducir la ansiedad y proteger de la crítica.",
  },
  CARE: {
    key: "CARE", name: "Cuidador / Rescatador", role: "Manager (Gestor)", proposed: false,
    triggers: "Sufrimiento ajeno, culpa por poner límites, \"ser egoísta\".",
    visibleBehaviour: "Sostiene, salva, contiene; prioriza a otros; no pide ayuda.",
    strategy: "Ser útil para asegurar el vínculo y el valor propio.",
    wound: "Partes como esta suelen proteger un rol temprano de sostén hacia los demás, y un miedo a no ser querido o querida si no aporta.",
    sourceWound: "Parentificación o rol temprano de sostén; miedo a no ser querido/a si no aporta.",
    cost: "Sobrecarga, agotamiento, relaciones asimétricas, resentimiento.",
    protectiveNeed: "Mantener la conexión siendo indispensable.",
  },
  HYPV: {
    key: "HYPV", name: "Hipervigilante / Ansioso", role: "Manager (Gestor)", proposed: false,
    triggers: "Ambigüedad social, señales de amenaza, noticias, síntomas, silencio del otro.",
    visibleBehaviour: "Rumia, chequea, busca garantías, anticipa lo peor.",
    strategy: "Escanear el peligro y preparar una respuesta.",
    wound: "Partes como esta suelen proteger a una parte más joven que conoció la inseguridad o la amenaza temprano, y que carga un miedo crónico.",
    sourceWound: "Inseguridad/amenaza temprana; exiliado con miedo crónico.",
    cost: "Insomnio, fatiga, tensión, dificultad para estar presente.",
    protectiveNeed: "Detectar y prevenir el daño antes de que ocurra.",
  },
  DIST: {
    key: "DIST", name: "Distante / Autosuficiente", role: "Manager (Gestor)", proposed: false,
    triggers: "Dependencia emocional, pedir ayuda, intimidad profunda, sentirse \"necesitado/a\".",
    visibleBehaviour: "Se enfría, se retira, minimiza necesidades, evita conversaciones íntimas.",
    strategy: "\"No necesito a nadie\", para no sufrir.",
    wound: "Partes como esta suelen proteger un dolor de apego, un miedo al abandono o al rechazo, y a volver a necesitar sin respuesta.",
    sourceWound: "Dolor de apego; miedo a abandono/rechazo y a volver a necesitar sin respuesta.",
    cost: "Soledad, poca nutrición afectiva, vínculos superficiales, dificultad para recibir.",
    protectiveNeed: "Evitar la vulnerabilidad relacional y conservar el control interno.",
  },
  NUMB: {
    key: "NUMB", name: "Anestesiador / Consumidor", role: "Firefighter (Bombero)", proposed: false,
    triggers: "Dolor, soledad, vergüenza, recuerdos, conflicto o colapso del control.",
    visibleBehaviour: "Pantallas, comida, sustancias, sexo, trabajo excesivo; cualquier cosa que apague rápido la emoción.",
    strategy: "Anestesiar rápido para bajar la intensidad.",
    wound: "Partes como esta suelen proteger una tristeza, un terror o una soledad que se han mantenido fuera de la vista.",
    sourceWound: "Tristeza, terror o soledad exiliada.",
    cost: "Adicción conductual, desconexión, salud afectada, problemas de pareja.",
    protectiveNeed: "Alivio inmediato.",
  },
  DISS: {
    key: "DISS", name: "Desconectado / Disociador", role: "Firefighter (Bombero), a veces Manager", proposed: true,
    triggers: "Desborde, conflicto, recuerdos dolorosos, sentirse observado de cerca, emoción intensa en el cuerpo.",
    visibleBehaviour: "Se queda en blanco, nublado o lejos; pierde tiempo; se siente irreal o fuera del cuerpo; no encuentra palabras.",
    strategy: "Irse de la escena por dentro cuando no es posible irse por fuera.",
    wound: "Partes como esta suelen proteger un terror o una indefensión de momentos que fueron demasiado y de los que no se pudo escapar.",
    sourceWound: "Escala propuesta; sin fuente en el material original.",
    cost: "Tiempo perdido, ausencia en las relaciones, dificultad para aprender de la experiencia, sensación de irrealidad.",
    protectiveNeed: "Distancia de lo que se siente insoportable.",
  },
  ANGR: {
    key: "ANGR", name: "Ira protectora / Explosivo", role: "Firefighter (Bombero)", proposed: false,
    triggers: "Invalidación, humillación, control externo, amenaza a los límites o a la identidad.",
    visibleBehaviour: "Ataque, sarcasmo, intimidación, sube el volumen, corta la conversación.",
    strategy: "Recuperar el poder rápido para no sentirse pequeño o pequeña.",
    wound: "Partes como esta suelen proteger indefensión y vergüenza, y experiencias de no haber podido defenderse.",
    sourceWound: "Indefensión y vergüenza; experiencias de no poder defenderse.",
    cost: "Daño relacional, culpa posterior, aislamiento, escaladas.",
    protectiveNeed: "Restaurar los límites y la sensación de poder.",
  },
  IMPL: {
    key: "IMPL", name: "Impulsivo / Escapista", role: "Firefighter (Bombero)", proposed: true,
    triggers: "Sentirse atrapado, presión, aburrimiento que esconde dolor, vergüenza que sube.",
    visibleBehaviour: "Salidas repentinas, renuncias, rupturas, gastos, riesgos; actuar primero y pensar después.",
    strategy: "Cambiar la situación de inmediato para que la emoción pare.",
    wound: "Partes como esta suelen proteger una sensación de estar atrapado o sin poder, sin voz sobre lo que ocurre.",
    sourceWound: "Escala propuesta; sin fuente en el material original.",
    cost: "Compromisos rotos, daño económico o relacional, arrepentimiento, pérdida de la confianza de otros.",
    protectiveNeed: "Libertad y alivio inmediato de la presión.",
  },
  REBL: {
    key: "REBL", name: "Rebelde / Desafiante", role: "Manager o Firefighter (Gestor o Bombero)", proposed: false,
    triggers: "Autoridad rígida, normas impuestas, sentirse controlado o invadido.",
    visibleBehaviour: "Oposición automática, provocación, \"no me mandas\", sabotaje pasivo o activo.",
    strategy: "Resistir para recuperar autonomía y dignidad.",
    wound: "Partes como esta suelen proteger un miedo al sometimiento, y a una parte más joven que carga indefensión y rabia contenida.",
    sourceWound: "Miedo a sometimiento; exiliado con indefensión y rabia contenida.",
    cost: "Conflicto crónico, dificultad para colaborar, aislamiento, oportunidades perdidas.",
    protectiveNeed: "Autonomía, límites claros y respeto.",
  },
};
