/**
 * DRAFT, pending human review.
 * Protector content, Turkish. Translated from the Spanish master and the English
 * draft. `wound` in tentative voice; `sourceWound` keeps the source wording.
 */
import type { ProtectorKey } from "@/lib/scoring/types";
import type { Typology } from "./typologies.en";

export const MICRO_QUESTION_TR = "Bunu yaptığında beni neyi hissetmekten ya da hatırlamaktan koruyorsun?";

export const TYPOLOGIES_TR: Record<ProtectorKey, Typology> = {
  PERF: { key: "PERF", name: "Mükemmeliyetçi / Talepkâr", role: "Yönetici (Manager)", proposed: false,
    triggers: "Değerlendirme, hata, kıyaslama, yüksek standartlı işler, kamuya açık olma.",
    visibleBehaviour: "Düzeltir, tekrar kontrol eder, teslim etmez, kendini fazla zorlar, \"mükemmeli\" arar.",
    strategy: "\"Mükemmel yaparsam güvendeyim.\"",
    wound: "Böyle parçalar çoğu zaman hataya bağlı bir utancı, yeterli olmama hissini ve aşağılanma ya da reddedilme korkusunu korur.",
    sourceWound: "Vergüenza por error; \"no soy suficiente\"; miedo a humillación o rechazo.",
    cost: "Kaygı, katılık, erteleme, az keyif, ilişkilerde yıpranma.",
    protectiveNeed: "Performans yoluyla güvenlik ve kabul." },
  CRIT: { key: "CRIT", name: "Eleştirmen / Yargıç", role: "Yönetici (Manager)", proposed: false,
    triggers: "Kırılganlık, geri bildirim, iç şüpheler, kendinin ya da başkalarının \"hataları\".",
    visibleBehaviour: "Değersizleştirir, ahlak dersi verir, içte ya da dışta tonu sertleştirir, kusurları gösterir.",
    strategy: "Saldırıya uğramadan önce saldır: \"Seni önce ben eleştirirsem, dışarıda kimse seni incitemez.\"",
    wound: "Böyle parçalar çoğu zaman eski bir eleştirilme ya da aşağılanma deneyimini ve utançla korku taşıyan daha genç bir parçayı korur.",
    sourceWound: "Historia de crítica o humillación; exiliado con vergüenza y miedo.",
    cost: "Kendini cezalandırma, suçluluk, donma, düşmanlık, duygusal mesafe.",
    protectiveNeed: "Açıkta kalmaktan kaçınmak ve kontrolü elde tutmak." },
  PLEA: { key: "PLEA", name: "Memnun Edici", role: "Yönetici (Manager)", proposed: false,
    triggers: "Çatışma, onaylanmama, otorite figürleri, sınır koymak.",
    visibleBehaviour: "Evet der, uyum sağlar, karşı çıkmaktan kaçınır, fazla sorumluluk üstlenir.",
    strategy: "Bağı güvence altına almak için uyumu korumak.",
    wound: "Böyle parçalar çoğu zaman terk edilme ya da reddedilme korkusunu ve güvende hissetmek için hoşa gitme yönündeki erken bir ihtiyacı korur.",
    sourceWound: "Miedo a abandono o rechazo; necesidad temprana de agradar para estar seguro/a.",
    cost: "Kırgınlık, tükenme, bulanık kimlik, zayıf sınırlar.",
    protectiveNeed: "Aidiyet ve ilişkide güvenlik." },
  CTRL: { key: "CTRL", name: "Kontrolcü / Planlayıcı", role: "Yönetici (Manager)", proposed: false,
    triggers: "Belirsizlik, değişiklikler, muğlaklık, başkasına bağımlı olmak.",
    visibleBehaviour: "Katı program, kurallar, denetler, düzeltir, senaryoları önceden görür.",
    strategy: "Güvende olmak için öngörmek ve kontrol etmek.",
    wound: "Böyle parçalar çoğu zaman öngörülemezlik ya da kaosla karşılaşmış, korku ve çaresizlik taşıyan daha genç bir parçayı korur.",
    sourceWound: "Imprevisibilidad/caos temprano; exiliado con miedo e indefensión.",
    cost: "Kronik gerginlik, sinirlilik, katılık, yetki devretmede zorluk.",
    protectiveNeed: "İstikrar ve zararın önlenmesi." },
  INTL: { key: "INTL", name: "Entelektüelleştirici / Rasyonelleştirici", role: "Yönetici (Manager)", proposed: false,
    triggers: "Yoğun duygu, yakınlık, acı, suçluluk, kararsızlık, duygusal konuşmalar.",
    visibleBehaviour: "Analiz eder, kuram kurar, tartışır, açıklar; bedenden kopar.",
    strategy: "Yoğunluğu düzenlemek için duyguyu düşünceye çevirmek.",
    wound: "Böyle parçalar çoğu zaman bir zamanlar \"fazla\" gelmiş bir acıyı ya da utancı ve taşmaktan duyulan korkuyu korur.",
    sourceWound: "Dolor/vergüenza \"demasiado\"; miedo a desbordarse.",
    cost: "Duygusal kopukluk, az yakınlık, boşluk, destek istemede zorluk.",
    protectiveNeed: "Kırılganlıktan ve taşmaktan kaçınmak; netliği ve kesinliği korumak." },
  AVOI: { key: "AVOI", name: "Kaçınan / Erteleyici", role: "Yönetici (Manager)", proposed: false,
    triggers: "Başarısızlık riski taşıyan işler, değerlendirme, kararlar, önemli hedefler.",
    visibleBehaviour: "Erteler, dikkati dağılır, başlamaktan kaçınır, anında rahatlama arar.",
    strategy: "Kaygılı uyarılmadan ve değerlendirmeye maruz kalmaktan kaçınmak.",
    wound: "Böyle parçalar çoğu zaman önceden hissedilen bir utancı, başarısız olma korkusunu ve bir güçsüzlük hissini korur.",
    sourceWound: "Vergüenza anticipada; miedo a fracasar; impotencia.",
    cost: "Suçluluk, kaçırılan fırsatlar, biriken baskı, zedelenmiş öz imge.",
    protectiveNeed: "Kaygıyı azaltmak ve eleştiriden korumak." },
  CARE: { key: "CARE", name: "Bakım Veren / Kurtarıcı", role: "Yönetici (Manager)", proposed: false,
    triggers: "Başkalarının acısı, sınır koymanın suçluluğu, \"bencil olmak\".",
    visibleBehaviour: "Taşır, kurtarır, kapsar; başkalarını öne koyar; yardım istemez.",
    strategy: "Bağı ve değer hissini güvence altına almak için işe yaramak.",
    wound: "Böyle parçalar çoğu zaman başkalarını ayakta tutma yönündeki erken bir rolü ve katkı sunmadıkça sevilmeme korkusunu korur.",
    sourceWound: "Parentificación o rol temprano de sostén; miedo a no ser querido/a si no aporta.",
    cost: "Aşırı yük, tükenme, tek taraflı ilişkiler, kırgınlık.",
    protectiveNeed: "Vazgeçilmez olarak bağı korumak." },
  HYPV: { key: "HYPV", name: "Aşırı Tetikte / Kaygılı", role: "Yönetici (Manager)", proposed: false,
    triggers: "Sosyal belirsizlik, tehdit işaretleri, haberler, belirtiler, karşıdakinin sessizliği.",
    visibleBehaviour: "Kafa yorar, kontrol eder, güvence arar, en kötüsünü bekler.",
    strategy: "Tehlikeyi taramak ve bir yanıt hazırlamak.",
    wound: "Böyle parçalar çoğu zaman erken dönemde güvensizlik ya da tehditle karşılaşmış, kronik bir korku taşıyan daha genç bir parçayı korur.",
    sourceWound: "Inseguridad/amenaza temprana; exiliado con miedo crónico.",
    cost: "Uykusuzluk, yorgunluk, gerginlik, anda kalmada zorluk.",
    protectiveNeed: "Zararı olmadan önce tespit etmek ve önlemek." },
  DIST: { key: "DIST", name: "Mesafeli / Kendine Yeten", role: "Yönetici (Manager)", proposed: false,
    triggers: "Duygusal bağımlılık, yardım istemek, derin yakınlık, \"muhtaç\" hissetmek.",
    visibleBehaviour: "Soğur, geri çekilir, ihtiyaçlarını küçümser, yakın konuşmalardan kaçınır.",
    strategy: "Acı çekmemek için \"kimseye ihtiyacım yok\".",
    wound: "Böyle parçalar çoğu zaman bir bağlanma acısını, terk edilme ya da reddedilme korkusunu ve yeniden karşılıksız ihtiyaç duyma korkusunu korur.",
    sourceWound: "Dolor de apego; miedo a abandono/rechazo y a volver a necesitar sin respuesta.",
    cost: "Yalnızlık, az duygusal besin, yüzeysel bağlar, almakta zorluk.",
    protectiveNeed: "İlişkide kırılganlıktan kaçınmak ve iç kontrolü korumak." },
  NUMB: { key: "NUMB", name: "Yatıştırıcı / Tüketici", role: "İtfaiyeci (Firefighter)", proposed: false,
    triggers: "Acı, yalnızlık, utanç, anılar, çatışma ya da kontrolün çökmesi.",
    visibleBehaviour: "Ekranlar, yemek, maddeler, seks, aşırı çalışma; duyguyu hızla kapatan her şey.",
    strategy: "Yoğunluğu düşürmek için hızla uyuşturmak.",
    wound: "Böyle parçalar çoğu zaman gözden uzak tutulmuş bir hüznü, dehşeti ya da yalnızlığı korur.",
    sourceWound: "Tristeza, terror o soledad exiliada.",
    cost: "Davranışsal bağımlılık, kopukluk, sağlığın etkilenmesi, ilişkide sorunlar.",
    protectiveNeed: "Anında rahatlama." },
  DISS: { key: "DISS", name: "Kopan / Disosiye Olan", role: "İtfaiyeci (Firefighter), bazen Yönetici", proposed: true,
    triggers: "Bunalma, çatışma, acı veren anılar, yakından bakılmak, bedende yoğun duygu.",
    visibleBehaviour: "Boşalır, bulanıklaşır ya da uzaklaşır; zamanı kaybeder; gerçek dışı ya da bedenin dışında hisseder; kelime bulamaz.",
    strategy: "Dışarı çıkmak mümkün olmadığında içten sahneyi terk etmek.",
    wound: "Böyle parçalar çoğu zaman fazla gelen ve kaçılamayan anlardan kalan bir dehşeti ya da çaresizliği korur.",
    sourceWound: "Önerilen ölçek; özgün materyalde kaynağı yok.",
    cost: "Kayıp zaman, ilişkilerde yokluk, deneyimden öğrenmede zorluk, gerçek dışılık hissi.",
    protectiveNeed: "Dayanılmaz gelenden uzaklık." },
  ANGR: { key: "ANGR", name: "Koruyucu Öfke / Patlayıcı", role: "İtfaiyeci (Firefighter)", proposed: false,
    triggers: "Yok sayılma, aşağılanma, dış kontrol, sınırlara ya da kimliğe tehdit.",
    visibleBehaviour: "Saldırır, iğneler, gözdağı verir, sesini yükseltir, konuşmayı keser.",
    strategy: "Küçük hissetmemek için gücü hızla geri almak.",
    wound: "Böyle parçalar çoğu zaman çaresizliği ve utancı, kendini savunamamış olma deneyimlerini korur.",
    sourceWound: "Indefensión y vergüenza; experiencias de no poder defenderse.",
    cost: "İlişkilerde hasar, sonradan suçluluk, yalnızlaşma, tırmanmalar.",
    protectiveNeed: "Sınırları ve güç hissini yeniden kurmak." },
  IMPL: { key: "IMPL", name: "Dürtüsel / Kaçan", role: "İtfaiyeci (Firefighter)", proposed: true,
    triggers: "Kapana kısılmış hissetmek, baskı, acıyı gizleyen can sıkıntısı, yükselen utanç.",
    visibleBehaviour: "Ani çıkışlar, istifalar, kopuşlar, harcamalar, risk almak; önce yapıp sonra düşünmek.",
    strategy: "Duygu dursun diye durumu bir anda değiştirmek.",
    wound: "Böyle parçalar çoğu zaman kapana kısılmış ya da güçsüz olma, olan bitende söz hakkı olmama hissini korur.",
    sourceWound: "Önerilen ölçek; özgün materyalde kaynağı yok.",
    cost: "Bozulan taahhütler, maddi ya da ilişkisel zarar, pişmanlık, başkalarının güvenini kaybetmek.",
    protectiveNeed: "Özgürlük ve baskıdan anında kurtulmak." },
  REBL: { key: "REBL", name: "Asi / Meydan Okuyan", role: "Yönetici ya da İtfaiyeci (Manager or Firefighter)", proposed: false,
    triggers: "Katı otorite, dayatılan kurallar, kontrol edilme ya da istila edilme hissi.",
    visibleBehaviour: "Otomatik karşı çıkış, kışkırtma, \"bana emir veremezsin\", pasif ya da aktif sabotaj.",
    strategy: "Özerkliği ve onuru geri kazanmak için direnmek.",
    wound: "Böyle parçalar çoğu zaman boyun eğdirilme korkusunu ve çaresizlikle bastırılmış öfke taşıyan daha genç bir parçayı korur.",
    sourceWound: "Miedo a sometimiento; exiliado con indefensión y rabia contenida.",
    cost: "Kronik çatışma, iş birliğinde zorluk, yalnızlaşma, kaçırılan fırsatlar.",
    protectiveNeed: "Özerklik, net sınırlar ve saygı." },
};
