/**
 * DRAFT, pending human review.
 * Protector content, Romanian. Translated from the Spanish master and the
 * English draft. `wound` in tentative voice; `sourceWound` keeps the source.
 */
import type { ProtectorKey } from "@/lib/scoring/types";
import type { Typology } from "./typologies.en";

export const MICRO_QUESTION_RO = "De ce mă ferești, ce nu mă lași să simt sau să-mi amintesc atunci când faci asta?";

export const TYPOLOGIES_RO: Record<ProtectorKey, Typology> = {
  PERF: {
    key: "PERF", name: "Perfecționist / Exigent", role: "Manager", proposed: false,
    triggers: "Evaluare, greșeală, comparație, sarcini cu standard înalt, expunere publică.",
    visibleBehaviour: "Corectează, verifică, nu predă, se suprasolicită, caută „perfectul”.",
    strategy: "„Dacă fac perfect, sunt în siguranță.”",
    wound: "Părți ca aceasta protejează adesea o rușine legată de greșeală, un sentiment că nu ești de ajuns și o teamă de umilire sau respingere.",
    sourceWound: "Vergüenza por error; \"no soy suficiente\"; miedo a humillación o rechazo.",
    cost: "Anxietate, rigiditate, amânare, puțină bucurie, uzură în relații.",
    protectiveNeed: "Siguranță și acceptare prin performanță.",
  },
  CRIT: {
    key: "CRIT", name: "Critic / Judecător", role: "Manager", proposed: false,
    triggers: "Vulnerabilitate, feedback, îndoieli interioare, „greșeli” proprii sau ale altora.",
    visibleBehaviour: "Descalifică, moralizează, înăsprește tonul interior sau exterior, arată defecte.",
    strategy: "Atacă înainte de a fi atacat: „dacă te critic eu primul, afară nu te mai rănesc.”",
    wound: "Părți ca aceasta protejează adesea o istorie de critică sau umilire și o parte mai tânără care poartă rușine și frică.",
    sourceWound: "Historia de crítica o humillación; exiliado con vergüenza y miedo.",
    cost: "Autopedepsire, vinovăție, blocaj, ostilitate, distanță afectivă.",
    protectiveNeed: "Să evite expunerea și să păstreze controlul.",
  },
  PLEA: {
    key: "PLEA", name: "Cel care mulțumește pe toată lumea", role: "Manager", proposed: false,
    triggers: "Conflict, dezaprobare, figuri de autoritate, stabilirea limitelor.",
    visibleBehaviour: "Spune da, se adaptează, evită să contrazică, își asumă prea multă responsabilitate.",
    strategy: "Păstrează armonia ca să asigure legătura.",
    wound: "Părți ca aceasta protejează adesea o teamă de abandon sau respingere și o nevoie timpurie de a fi pe plac pentru a se simți în siguranță.",
    sourceWound: "Miedo a abandono o rechazo; necesidad temprana de agradar para estar seguro/a.",
    cost: "Resentiment, epuizare, identitate neclară, limite slabe.",
    protectiveNeed: "Apartenență și siguranță în relații.",
  },
  CTRL: {
    key: "CTRL", name: "Controlor / Planificator", role: "Manager", proposed: false,
    triggers: "Incertitudine, schimbări, ambiguitate, dependența de altcineva.",
    visibleBehaviour: "Program rigid, reguli, supraveghează, corectează, anticipează scenarii.",
    strategy: "Prezice și controlează ca să fie în siguranță.",
    wound: "Părți ca aceasta protejează adesea o parte mai tânără care a cunoscut imprevizibilul sau haosul și care poartă frică și neputință.",
    sourceWound: "Imprevisibilidad/caos temprano; exiliado con miedo e indefensión.",
    cost: "Tensiune cronică, iritabilitate, rigiditate, dificultate de a delega.",
    protectiveNeed: "Stabilitate și prevenirea răului.",
  },
  INTL: {
    key: "INTL", name: "Intelectualizator / Raționalizator", role: "Manager", proposed: false,
    triggers: "Emoție intensă, intimitate, durere, vinovăție, ambivalență, conversații afective.",
    visibleBehaviour: "Analizează, teoretizează, dezbate, explică; se deconectează de corp.",
    strategy: "Transformă emoția în gând ca să regleze intensitatea.",
    wound: "Părți ca aceasta protejează adesea o durere sau o rușine care au fost cândva „prea mult” și o teamă de a fi copleșit.",
    sourceWound: "Dolor/vergüenza \"demasiado\"; miedo a desbordarse.",
    cost: "Deconectare emoțională, puțină intimitate, gol, dificultate de a cere sprijin.",
    protectiveNeed: "Să evite vulnerabilitatea și copleșirea; să păstreze claritatea și certitudinea.",
  },
  AVOI: {
    key: "AVOI", name: "Evitant / Amânător", role: "Manager", proposed: false,
    triggers: "Sarcini cu risc de eșec, evaluare, decizii, obiective importante.",
    visibleBehaviour: "Amână, se distrage, evită să înceapă, caută ușurare imediată.",
    strategy: "Evită activarea anxioasă și expunerea la evaluare.",
    wound: "Părți ca aceasta protejează adesea o rușine anticipată, o teamă de eșec și un sentiment de neputință.",
    sourceWound: "Vergüenza anticipada; miedo a fracasar; impotencia.",
    cost: "Vinovăție, ocazii pierdute, presiune acumulată, imagine de sine afectată.",
    protectiveNeed: "Să reducă anxietatea și să protejeze de critică.",
  },
  CARE: {
    key: "CARE", name: "Îngrijitor / Salvator", role: "Manager", proposed: false,
    triggers: "Suferința altora, vinovăția de a pune limite, „a fi egoist”.",
    visibleBehaviour: "Susține, salvează, conține; îi pune pe alții pe primul loc; nu cere ajutor.",
    strategy: "Fii util ca să asiguri legătura și valoarea proprie.",
    wound: "Părți ca aceasta protejează adesea un rol timpuriu de sprijin pentru ceilalți și o teamă de a nu fi iubit dacă nu contribuie.",
    sourceWound: "Parentificación o rol temprano de sostén; miedo a no ser querido/a si no aporta.",
    cost: "Suprasolicitare, epuizare, relații dezechilibrate, resentiment.",
    protectiveNeed: "Să păstreze conexiunea fiind indispensabil.",
  },
  HYPV: {
    key: "HYPV", name: "Hipervigilent / Anxios", role: "Manager", proposed: false,
    triggers: "Ambiguitate socială, semne de amenințare, știri, simptome, tăcerea celuilalt.",
    visibleBehaviour: "Rumegă, verifică, caută garanții, anticipează ce e mai rău.",
    strategy: "Scanează pericolul și pregătește un răspuns.",
    wound: "Părți ca aceasta protejează adesea o parte mai tânără care a cunoscut devreme nesiguranța sau amenințarea și care poartă o frică cronică.",
    sourceWound: "Inseguridad/amenaza temprana; exiliado con miedo crónico.",
    cost: "Insomnie, oboseală, tensiune, dificultate de a fi prezent.",
    protectiveNeed: "Să detecteze și să prevină răul înainte să se întâmple.",
  },
  DIST: {
    key: "DIST", name: "Distant / Autosuficient", role: "Manager", proposed: false,
    triggers: "Dependență emoțională, a cere ajutor, intimitate profundă, a se simți „în nevoie”.",
    visibleBehaviour: "Se răcește, se retrage, își minimalizează nevoile, evită conversațiile intime.",
    strategy: "„Nu am nevoie de nimeni”, ca să nu sufere.",
    wound: "Părți ca aceasta protejează adesea o durere de atașament, o teamă de abandon sau respingere și de a avea din nou nevoie fără răspuns.",
    sourceWound: "Dolor de apego; miedo a abandono/rechazo y a volver a necesitar sin respuesta.",
    cost: "Singurătate, puțină hrană afectivă, legături superficiale, dificultate de a primi.",
    protectiveNeed: "Să evite vulnerabilitatea relațională și să păstreze controlul interior.",
  },
  NUMB: {
    key: "NUMB", name: "Cel care amorțește / Consumator", role: "Firefighter (Pompier)", proposed: false,
    triggers: "Durere, singurătate, rușine, amintiri, conflict sau prăbușirea controlului.",
    visibleBehaviour: "Ecrane, mâncare, substanțe, sex, muncă excesivă; orice stinge repede emoția.",
    strategy: "Amorțește rapid ca să scadă intensitatea.",
    wound: "Părți ca aceasta protejează adesea o tristețe, o teroare sau o singurătate ținute departe de privire.",
    sourceWound: "Tristeza, terror o soledad exiliada.",
    cost: "Dependență comportamentală, deconectare, sănătate afectată, probleme în cuplu.",
    protectiveNeed: "Ușurare imediată.",
  },
  DISS: {
    key: "DISS", name: "Deconectat / Disociativ", role: "Firefighter (Pompier), uneori Manager", proposed: true,
    triggers: "Copleșire, conflict, amintiri dureroase, a fi privit de aproape, emoție intensă în corp.",
    visibleBehaviour: "Se golește, se încețoșează sau se îndepărtează; pierde timp; se simte ireal sau în afara corpului; nu găsește cuvinte.",
    strategy: "Pleacă din scenă pe dinăuntru când nu se poate pleca pe dinafară.",
    wound: "Părți ca aceasta protejează adesea o teroare sau o neputință din momente care au fost prea mult și din care nu se putea scăpa.",
    sourceWound: "Scală propusă; fără sursă în materialul original.",
    cost: "Timp pierdut, absență în relații, dificultate de a învăța din experiență, senzație de irealitate.",
    protectiveNeed: "Distanță de ceea ce pare de nesuportat.",
  },
  ANGR: {
    key: "ANGR", name: "Furie protectoare / Exploziv", role: "Firefighter (Pompier)", proposed: false,
    triggers: "Invalidare, umilire, control extern, amenințare la adresa limitelor sau identității.",
    visibleBehaviour: "Atac, sarcasm, intimidare, ridică vocea, taie conversația.",
    strategy: "Recuperează rapid puterea ca să nu se simtă mic.",
    wound: "Părți ca aceasta protejează adesea neputință și rușine, și experiențe de a nu se fi putut apăra.",
    sourceWound: "Indefensión y vergüenza; experiencias de no poder defenderse.",
    cost: "Rănirea relațiilor, vinovăție ulterioară, izolare, escaladări.",
    protectiveNeed: "Să restabilească limitele și sentimentul de putere.",
  },
  IMPL: {
    key: "IMPL", name: "Impulsiv / Evadant", role: "Firefighter (Pompier)", proposed: true,
    triggers: "Senzația de a fi prins în capcană, presiune, plictiseală care ascunde durere, rușine care crește.",
    visibleBehaviour: "Ieșiri bruște, demisii, rupturi, cheltuieli, riscuri; acționează întâi și gândește apoi.",
    strategy: "Schimbă situația pe loc ca emoția să se oprească.",
    wound: "Părți ca aceasta protejează adesea un sentiment de a fi prins sau fără putere, fără niciun cuvânt de spus despre ce se întâmplă.",
    sourceWound: "Scală propusă; fără sursă în materialul original.",
    cost: "Angajamente rupte, pagube financiare sau relaționale, regret, pierderea încrederii celorlalți.",
    protectiveNeed: "Libertate și ușurare imediată de presiune.",
  },
  REBL: {
    key: "REBL", name: "Rebel / Sfidător", role: "Manager sau Firefighter (Pompier)", proposed: false,
    triggers: "Autoritate rigidă, reguli impuse, senzația de a fi controlat sau invadat.",
    visibleBehaviour: "Opoziție automată, provocare, „nu-mi spui tu ce să fac”, sabotaj pasiv sau activ.",
    strategy: "Rezistă ca să-și recapete autonomia și demnitatea.",
    wound: "Părți ca aceasta protejează adesea o teamă de supunere și o parte mai tânără care poartă neputință și furie reținută.",
    sourceWound: "Miedo a sometimiento; exiliado con indefensión y rabia contenida.",
    cost: "Conflict cronic, dificultate de a colabora, izolare, ocazii pierdute.",
    protectiveNeed: "Autonomie, limite clare și respect.",
  },
};
